[package]
name = "rl-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "rl-engine: rl-ui"

[dependencies]
rl-core.workspace = true
rl-bevy.workspace = true
bevy.workspace = true
rl-render.workspace = true
