[package]
name = "rl-test-support"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "rl-engine: rl-test-support"

[dependencies]
rl-core.workspace = true
rl-grid.workspace = true
rl-world.workspace = true
