[package]
name = "rl-bevy"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "rl-engine: rl-bevy"

[dependencies]
rl-core.workspace = true
rl-grid.workspace = true
rl-mapgen.workspace = true
rl-world.workspace = true
rl-content.workspace = true
rl-rules.workspace = true
rl-ai.workspace = true
rl-events.workspace = true
rand = { workspace = true, features = ["std", "std_rng"] }
bevy.workspace = true
